# Generated by Django 5.2.1 on 2025-06-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('failed', 'Failed'), ('completed', 'Completed')], default='completed', max_length=20),
        ),
    ]
